// Copyright (c) 2016-2025 Association of Universities for Research in Astronomy, Inc. (AURA)
// For license information see LICENSE or https://opensource.org/licenses/BSD-3-Clause

package lucuma.core.math

import cats.Eq
import cats.Show
import cats.implicits.*
import cats.kernel.laws.discipline.*
import lucuma.core.arb.ArbTime
import lucuma.core.math.arb.*
import lucuma.core.math.parser.EpochParsers.*
import lucuma.core.optics.laws.discipline.*
import lucuma.refined.*
import monocle.law.discipline.PrismTests
import org.scalacheck.Arbitrary
import org.scalacheck.Prop.*

import java.time.LocalDateTime

final class EpochSuite extends munit.DisciplineSuite {
  import ArbEpoch.given
  import ArbTime.given

  // provide an Arbitrary[String] for the Prism tests.
  given Arbitrary[String] = Arbitrary(ArbEpoch.strings)

  // Laws
  checkAll("Epoch", OrderTests[Epoch].order)
  checkAll("fromString", PrismTests(Epoch.fromString))
  checkAll("fromStringNoScheme",
           FormatTests(Epoch.fromStringNoScheme)
             .formatWith(ArbEpoch.stringsNoScheme)(Eq[String], ArbEpoch.arbJulianEpoch, Eq[Epoch])
  )

  test("Epoch.eq.natural") {
    forAll { (a: Epoch, b: Epoch) =>
      assertEquals(a.equals(b), Eq[Epoch].eqv(a, b))
    }
  }

  test("Epoch.show.natural") {
    forAll { (a: Epoch) =>
      assertEquals(a.toString, Show[Epoch].show(a))
    }
  }

  test("Epoch.until.identity") {
    forAll { (a: Epoch) =>
      assertEquals(a.untilEpochYear(a.epochYear), 0.0)
    }
  }

  test("Epoch.until.sanity") {
    forAll { (a: Epoch, s: Short) =>
      assertEqualsDouble(a.untilEpochYear(a.epochYear + s.toDouble), s.toDouble, 0.005)
    }
  }

  test("Epoch.until.sanity2") {
    forAll { (s: Epoch.Scheme, d1: LocalDateTime, d2: LocalDateTime) =>
      // the dates generated by ArbTime are between years 2000 and 2020 and are safe for this.
      val Δ1 = s.fromLocalDateTime(d1).get.untilLocalDateTime(d2)
      val Δ2 = s.fromLocalDateTime(d2).get.epochYear - s.fromLocalDateTime(d1).get.epochYear
      assertEqualsDouble(Δ1, Δ2, 0.005)
    }
  }

  test("epochLenientNoScheme") {
    assertEquals(epochLenientNoScheme.parseAll("2014.123").toOption,
                 Epoch.Julian.fromMilliyears(2014123.refined).some
    )
    assertEquals(epochLenientNoScheme.parseAll("2014").toOption, Epoch.Julian.fromMilliyears(2014000.refined).some)
    assertEquals(epochLenientNoScheme.parseAll("2014.").toOption,
                 Epoch.Julian.fromMilliyears(2014000.refined).some
    )
    assertEquals(epochLenientNoScheme.parseAll("2014.1").toOption,
                 Epoch.Julian.fromMilliyears(2014100.refined).some
    )
    assertEquals(epochLenientNoScheme.parseAll("2014.092").toOption,
                 Epoch.Julian.fromMilliyears(2014092.refined).some
    )
    assertEquals(epochLenientNoScheme.parseAll("2014.002").toOption,
                 Epoch.Julian.fromMilliyears(2014002.refined).some
    )
    assertEquals(epochLenientNoScheme.parseAll("J2014.123").toOption, None)
    assertEquals(epochLenientNoScheme.parseAll("J2014").toOption, None)
    assertEquals(epochLenientNoScheme.parseAll("J2014.").toOption, None)
    assertEquals(epochLenientNoScheme.parseAll("J2014.1").toOption, None)
    assertEquals(epochLenientNoScheme.parseAll("B2014.123").toOption, None)
    assertEquals(epochLenientNoScheme.parseAll("B2014").toOption, None)
    assertEquals(epochLenientNoScheme.parseAll("B2014.").toOption, None)
    assertEquals(epochLenientNoScheme.parseAll("B2014.1").toOption, None)
  }

  test("epochFormatNoScheme") {
    assertEquals(Epoch.fromStringNoScheme.reverseGet(Epoch.Julian.fromMilliyears(2014123.refined)),
                 "2014.123"
    )
    assertEquals(Epoch.fromStringNoScheme.reverseGet(Epoch.Julian.fromMilliyears(2014000.refined)), "2014")
    assertEquals(Epoch.fromStringNoScheme.reverseGet(Epoch.Julian.fromMilliyears(2014300.refined)),
                 "2014.3"
    )
    assertEquals(Epoch.fromStringNoScheme.reverseGet(Epoch.Julian.fromMilliyears(2014092.refined)),
                 "2014.092"
    )
    assertEquals(Epoch.fromStringNoScheme.reverseGet(Epoch.Julian.fromMilliyears(2014002.refined)),
                 "2014.002"
    )
    assertEquals(Epoch.fromStringNoScheme.reverseGet(Epoch.Julian.fromMilliyears(2014350.refined)),
                 "2014.35"
    )
  }
}
